DROP DATABASE DMARC;
CREATE DATABASE DMARC;
CREATE TABLE RUA (
    record_id INTEGER,
    org_name VARCHAR(255),
    org_email VARCHAR(255),
    org_extra_contact_info VARCHAR(255),
    report_id VARCHAR(255),
    begin_date VARCHAR(255),
    end_date VARCHAR(255),
    domain VARCHAR(255),
    adkim VARCHAR(255),
    aspf VARCHAR(255),
    p VARCHAR(255),
    sp VARCHAR(255),
    pct INTEGER,
    fo INTEGER,
    source_ip_address VARCHAR(255),
    source_country VARCHAR(255),
    source_reverse_dns VARCHAR(255),
    source_base_domain VARCHAR(255),
    count INTEGER,
    spf_aligned VARCHAR(255),
    dkim_aligned VARCHAR(255),
    dmarc_aligned VARCHAR(255),
    disposition VARCHAR(255),
    envelope_from VARCHAR(255),
    header_from VARCHAR(255),
    envelope_to VARCHAR(255),
    dkim_domain VARCHAR(255),
    dkim_selector VARCHAR(255),
    dkim_result VARCHAR(255),
    spf_domain VARCHAR(255),
    spf_scope VARCHAR(255),
    spf_result VARCHAR(255),
    PRIMARY KEY (record_id)
);
INSERT INTO RUA (record_id, org_name, org_email, org_extra_contact_info, report_id, begin_date, end_date,
    domain, adkim, aspf, p, sp, pct, fo, source_ip_address, source_country, source_reverse_dns, source_base_domain,
    count, spf_aligned, dkim_aligned, dmarc_aligned, disposition, envelope_from, header_from, envelope_to, dkim_domain,
    dkim_selector, dkim_result, spf_domain, spf_scope, spf_result) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
SELECT * FROM RUA;